
name: 启动京东自动签到

on:
  schedule:
  # 中国时间的凌晨5:42执行
  - cron: "42 19 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install requests 
        fi
    - name: Run JDQianDao
      run: |
        python jd_sign.py
      env:
        IKU_PSD: ${{ secrets.IKU_PSD }}
